@ECHO OFF
CLS
ECHO ***************************************************************************
ECHO                                   NOTIFICATION!
ECHO ***************************************************************************
ECHO These commands are executed automaticallly when starting FreeDOS.
ECHO. 

testdisk.exe
reboot.com

ECHO.
ECHO No startup commands defined! You'll have to search FreeDOS yourself....
ECHO ***************************************************************************
ECHO.
ECHO.